// removed interface: XBAR_TCDM_BUS_64
// removed interface: XBAR_TCDM_BUS
// removed interface: XBAR_PERIPH_BUS
// removed interface: MESSAGE_BUS
// removed interface: XBAR_DEMUX_BUS
// removed interface: TCDM_BANK_MEM_BUS
// removed interface: UNICAD_MEM_BUS_64
// removed interface: UNICAD_MEM_BUS_32
// removed interface: TCDM_BUS
// removed interface: BBMUX_CONFIG_BUS
// removed interface: AXI_BUS
// removed interface: AXI_BUS_ASYNC
// removed interface: AXI_LITE
// removed interface: CLKGATE_CONFIG_BUS
// removed interface: MMU_CONFIG_BUS
// removed interface: BIST_BUS
// removed interface: BRAM_PORT
// removed interface: SP_ICACHE_CTRL_UNIT_BUS
// removed interface: MP_ICACHE_CTRL_UNIT_BUS
// removed interface: MP_PF_ICACHE_CTRL_UNIT_BUS
// removed interface: PRI_ICACHE_CTRL_UNIT_BUS
// removed interface: L0_CTRL_UNIT_BUS
// removed interface: APB_BUS
// removed interface: FLL_BUS
// removed interface: CORE_PREF_BUS
// removed interface: marx_apu_if
// removed interface: marx_arbiter_if
// removed interface: cpu_marx_if
