/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/l2_tcdm_demux.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/lint_2_apb.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/lint_2_axi.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/axi_2_lint/axi64_2_lint32.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/axi_2_lint/axi_read_ctrl.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/axi_2_lint/axi_write_ctrl.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/axi_2_lint/lint64_to_32.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/AddressDecoder_Req_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/AddressDecoder_Resp_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/ArbitrationTree_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/FanInPrimitive_Req_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/FanInPrimitive_Resp_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/MUX2_REQ_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/RequestBlock_L2_1CH.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/RequestBlock_L2_2CH.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/ResponseBlock_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/ResponseTree_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/RR_Flag_Req_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_L2/XBAR_L2.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/AddressDecoder_Req_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/AddressDecoder_Resp_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/ArbitrationTree_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/FanInPrimitive_Req_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/FanInPrimitive_Resp_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/MUX2_REQ_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/RequestBlock1CH_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/RequestBlock2CH_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/ResponseBlock_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/ResponseTree_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/RR_Flag_Req_BRIDGE.sv
/volume1/users/vjain/pulpissimo/ips/L2_tcdm_hybrid_interco/RTL/XBAR_BRIDGE/XBAR_BRIDGE.sv
-incdir /volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_axi_biu.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_axi_module.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_lint_biu.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_lint_module.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_crc32.v
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_or1k_biu.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_or1k_module.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_or1k_status_reg.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_top.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/bytefifo.v
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/syncflop.v
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/syncreg.v
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_tap_top.v
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adv_dbg_if.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_axionly_top.sv
/volume1/users/vjain/pulpissimo/ips/adv_dbg_if/rtl/adbg_lintonly_top.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb2per/apb2per.sv
-incdir /volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/adv_timer_apb_if.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/comparator.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/lut_4x4.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/out_filter.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/up_down_counter.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/input_stage.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/prescaler.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/apb_adv_timer.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/timer_cntrl.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_adv_timer/./rtl/timer_module.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_fll_if/apb_fll_if.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_gpio/./rtl/apb_gpio.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_node/src/apb_node.sv
/volume1/users/vjain/pulpissimo/ips/apb/apb_node/src/apb_node_wrap.sv
/volume1/users/vjain/pulpissimo/ips/apb_interrupt_cntrl/apb_interrupt_cntrl.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_pkg.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_intf.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_atop_filter.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_arbiter.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_address_resolver.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_to_axi_lite.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_lite_to_axi.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_lite_xbar.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_lite_cut.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_lite_multicut.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_lite_join.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_cut.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_multicut.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_join.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_modify_address.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_delayer.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_id_remap.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi/src/axi_test.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/cdc_2phase.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/clk_div.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/counter.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/edge_propagator_tx.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/fifo_v3.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/lfsr_8bit.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/lzc.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/mv_filter.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/onehot_to_bin.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/plru_tree.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/popcount.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/rr_arb_tree.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/rstgen_bypass.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/serial_deglitch.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/shift_reg.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/spill_register.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/stream_demux.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/stream_filter.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/stream_fork.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/stream_mux.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/sync.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/sync_wedge.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/edge_detect.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/id_queue.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/rstgen.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/stream_delay.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/fall_through_register.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/stream_arbiter_flushable.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/stream_register.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/stream_arbiter.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/clock_divider_counter.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/find_first_one.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/generic_LFSR_8bit.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/generic_fifo.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/generic_fifo_adv.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/pulp_sync.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/pulp_sync_wedge.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/clock_divider.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/fifo_v2.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/prioarbiter.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/rrarbiter.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/deprecated/fifo_v1.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/edge_propagator.sv
/volume1/users/vjain/pulpissimo/ips/common_cells/src/edge_propagator_rx.sv
-incdir /volume1/users/vjain/pulpissimo/ips/axi/axi_node/./src/
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/apb_regs_top.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_address_decoder_AR.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_address_decoder_AW.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_address_decoder_BR.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_address_decoder_BW.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_address_decoder_DW.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_AR_allocator.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_ArbitrationTree.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_AW_allocator.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_BR_allocator.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_BW_allocator.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_DW_allocator.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_FanInPrimitive_Req.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_multiplexer.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_node.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_node_intf_wrap.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_node_wrap_with_slices.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_regs_top.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_request_block.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_response_block.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_node/src/axi_RR_Flag_Req.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice/src/axi_single_slice.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice/src/axi_ar_buffer.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice/src/axi_aw_buffer.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice/src/axi_b_buffer.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice/src/axi_r_buffer.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice/src/axi_slice.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice/src/axi_w_buffer.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice/src/axi_slice_wrap.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/axi_slice_dc_master.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/axi_slice_dc_slave.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/dc_data_buffer.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/dc_full_detector.v
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/dc_synchronizer.v
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/dc_token_ring_fifo_din.v
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/dc_token_ring_fifo_dout.v
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/dc_token_ring.v
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/axi_slice_dc_master_wrap.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/axi_slice_dc_slave_wrap.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_slice_dc/src/axi_cdc.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_mem_if/src/axi2mem.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_mem_if/src/deprecated/axi_mem_if.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_mem_if/src/deprecated/axi_mem_if_wrap.sv
/volume1/users/vjain/pulpissimo/ips/axi/axi_mem_if/src/deprecated/axi_mem_if_var_latency.sv
-incdir /volume1/users/vjain/pulpissimo/ips/timer_unit/rtl
/volume1/users/vjain/pulpissimo/ips/timer_unit/./rtl/apb_timer_unit.sv
/volume1/users/vjain/pulpissimo/ips/timer_unit/./rtl/timer_unit.sv
/volume1/users/vjain/pulpissimo/ips/timer_unit/./rtl/timer_unit_counter.sv
/volume1/users/vjain/pulpissimo/ips/timer_unit/./rtl/timer_unit_counter_presc.sv
/volume1/users/vjain/pulpissimo/ips/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
/volume1/users/vjain/pulpissimo/ips/fpu_div_sqrt_mvp/hdl/control_mvp.sv
/volume1/users/vjain/pulpissimo/ips/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv
/volume1/users/vjain/pulpissimo/ips/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
/volume1/users/vjain/pulpissimo/ips/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
/volume1/users/vjain/pulpissimo/ips/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
/volume1/users/vjain/pulpissimo/ips/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
/volume1/users/vjain/pulpissimo/ips/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
-incdir /volume1/users/vjain/pulpissimo/ips/fpnew/../common_cells/include
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_pkg.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_cast_multi.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_classifier.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_divsqrt_multi.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_fma.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_fma_multi.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_noncomp.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_opgroup_block.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_opgroup_fmt_slice.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_opgroup_multifmt_slice.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_rounding.sv
/volume1/users/vjain/pulpissimo/ips/fpnew/src/fpnew_top.sv
-incdir /volume1/users/vjain/pulpissimo/ips/jtag_pulp/../../rtl/includes
/volume1/users/vjain/pulpissimo/ips/jtag_pulp/src/bscell.sv
/volume1/users/vjain/pulpissimo/ips/jtag_pulp/src/jtag_axi_wrap.sv
/volume1/users/vjain/pulpissimo/ips/jtag_pulp/src/jtag_enable.sv
/volume1/users/vjain/pulpissimo/ips/jtag_pulp/src/jtag_enable_synch.sv
/volume1/users/vjain/pulpissimo/ips/jtag_pulp/src/jtagreg.sv
/volume1/users/vjain/pulpissimo/ips/jtag_pulp/src/jtag_rst_synch.sv
/volume1/users/vjain/pulpissimo/ips/jtag_pulp/src/jtag_sync.sv
/volume1/users/vjain/pulpissimo/ips/jtag_pulp/src/tap_top.v
-incdir /volume1/users/vjain/pulpissimo/ips/riscv/./rtl/include
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/register_file_test_wrap.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_register_file_latch.sv
-incdir /volume1/users/vjain/pulpissimo/ips/riscv/./rtl/include
-incdir /volume1/users/vjain/pulpissimo/ips/riscv/../../rtl/includes
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/include/apu_core_package.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/include/riscv_defines.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/include/riscv_tracer_defines.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_alu.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_alu_basic.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_alu_div.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_compressed_decoder.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_controller.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_cs_registers.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_decoder.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_int_controller.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_ex_stage.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_hwloop_controller.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_hwloop_regs.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_id_stage.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_if_stage.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_load_store_unit.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_mult.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_prefetch_buffer.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_prefetch_L0_buffer.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_core.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_apu_disp.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_fetch_fifo.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_L0_buffer.sv
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_pmp.sv
-incdir /volume1/users/vjain/pulpissimo/ips/riscv/./rtl/include
/volume1/users/vjain/pulpissimo/ips/riscv/./rtl/riscv_tracer.sv
-incdir /volume1/users/vjain/pulpissimo/ips/riscv/tb/tb_riscv/include
-incdir /volume1/users/vjain/pulpissimo/ips/riscv/rtl/include
/volume1/users/vjain/pulpissimo/ips/riscv/tb/tb_riscv/include/perturbation_defines.sv
/volume1/users/vjain/pulpissimo/ips/riscv/tb/tb_riscv/riscv_simchecker.sv
/volume1/users/vjain/pulpissimo/ips/riscv/tb/tb_riscv/tb_riscv_core.sv
/volume1/users/vjain/pulpissimo/ips/riscv/tb/tb_riscv/riscv_perturbation.sv
/volume1/users/vjain/pulpissimo/ips/riscv/tb/tb_riscv/riscv_random_interrupt_generator.sv
/volume1/users/vjain/pulpissimo/ips/riscv/tb/tb_riscv/riscv_random_stall.sv
-incdir /volume1/users/vjain/pulpissimo/ips/ibex/rtl
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_pkg.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_alu.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_compressed_decoder.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_controller.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_cs_registers.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_decoder.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_ex_block.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_id_stage.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_if_stage.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_load_store_unit.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_multdiv_slow.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_multdiv_fast.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_prefetch_buffer.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_fetch_fifo.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_pmp.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_core.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_pkg.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_tracer_pkg.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_tracer.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_core_tracing.sv
/volume1/users/vjain/pulpissimo/ips/ibex/rtl/ibex_register_file_latch.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1r_1w_test_wrap.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1w_64b_multi_port_read_32b_1row.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1w_multi_port_read_1row.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1r_1w_all.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1r_1w_all_test_wrap.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1r_1w_be.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1r_1w.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1r_1w_1row.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1w_128b_multi_port_read_32b.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1w_64b_multi_port_read_32b.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1w_64b_1r_32b.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1w_multi_port_read_be.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_1w_multi_port_read.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_2r_1w_asymm.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_2r_1w_asymm_test_wrap.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_2r_2w.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_3r_2w.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_3r_2w_be.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_multi_way_1w_64b_multi_port_read_32b.sv
/volume1/users/vjain/pulpissimo/ips/scm/latch_scm/register_file_multi_way_1w_multi_port_read.sv
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/model/gf22_DCO_model.tc.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/model/gf22_FLL_model.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLLPkg.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_clk_divider.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_clk_period_quantizer.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_clock_gated.rtl.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_digital.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_dither_pattern_gen.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_glitchfree_clkdiv.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_glitchfree_clkmux.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_mux.rtl.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_loop_filter.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_reg.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_settling_monitor.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_synchroedge.vhd
/volume1/users/vjain/pulpissimo/ips/generic_FLL/fe/rtl/FLL_zerodelta.vhd
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/deprecated/cluster_clk_cells.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/deprecated/cluster_pwr_cells.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/deprecated/generic_memory.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/deprecated/generic_rom.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/deprecated/pad_functional.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/deprecated/pulp_buffer.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/deprecated/pulp_clk_cells.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/deprecated/pulp_pwr_cells.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/rtl/tc_clk.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/tc_pwr.sv
/volume1/users/vjain/pulpissimo/ips/tech_cells_generic/src/deprecated/pulp_clock_gating_async.sv
-incdir /volume1/users/vjain/pulpissimo/ips/udma/udma_core/./rtl
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/core/udma_ch_addrgen.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/core/udma_arbiter.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/core/udma_core.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/core/udma_rx_channels.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/core/udma_tx_channels.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/core/udma_stream_unit.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/udma_ctrl.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/udma_apb_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/io_clk_gen.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/io_event_counter.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/io_generic_fifo.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/io_tx_fifo.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/io_tx_fifo_mark.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/io_tx_fifo_dc.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/io_shiftreg.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/udma_dc_fifo.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/udma_clkgen.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_core/rtl/common/udma_clk_div_cnt.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_uart/rtl/udma_uart_reg_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_uart/rtl/udma_uart_top.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_uart/rtl/udma_uart_rx.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_uart/rtl/udma_uart_tx.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2c/rtl/udma_i2c_reg_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2c/rtl/udma_i2c_bus_ctrl.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2c/rtl/udma_i2c_control.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2c/rtl/udma_i2c_top.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/i2s_clk_gen.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/i2s_rx_channel.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/i2s_tx_channel.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/i2s_ws_gen.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/i2s_clkws_gen.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/i2s_txrx.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/cic_top.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/cic_integrator.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/cic_comb.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/pdm_top.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/udma_i2s_reg_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_i2s/rtl/udma_i2s_top.sv
-incdir /volume1/users/vjain/pulpissimo/ips/udma/udma_qspi/rtl
/volume1/users/vjain/pulpissimo/ips/udma/udma_qspi/rtl/udma_spim_reg_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_qspi/rtl/udma_spim_ctrl.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_qspi/rtl/udma_spim_txrx.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_qspi/rtl/udma_spim_top.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_sdio/rtl/sdio_crc7.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_sdio/rtl/sdio_crc16.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_sdio/rtl/sdio_txrx_cmd.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_sdio/rtl/sdio_txrx_data.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_sdio/rtl/sdio_txrx.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_sdio/rtl/udma_sdio_reg_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_sdio/rtl/udma_sdio_top.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_camera/rtl/camera_reg_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_camera/rtl/camera_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_filter/rtl/udma_filter_au.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_filter/rtl/udma_filter_bincu.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_filter/rtl/udma_filter_rx_dataout.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_filter/rtl/udma_filter_tx_datafetch.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_filter/rtl/udma_filter_reg_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_filter/rtl/udma_filter.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/RX_serializer.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/udma_mram_reg_if.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/udma_mram_top.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/size_conv_TX_32_to_64.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/size_conv_RX_64_to_32.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/TX_RX_to_MRAM.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/udma_dc_fifo_mram.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/dc_token_ring_fifo_din_mram.v
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/dc_full_detector_mram.v
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/udma_mram_macro_wrapper.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/udma_mram_domain.sv
/volume1/users/vjain/pulpissimo/ips/udma/udma_external_per/rtl/udma_mram_top_wrapper.sv
-incdir /volume1/users/vjain/pulpissimo/ips/hwpe-ctrl/rtl
/volume1/users/vjain/pulpissimo/ips/hwpe-ctrl/rtl/hwpe_ctrl_package.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-ctrl/rtl/hwpe_ctrl_interfaces.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-ctrl/rtl/hwpe_ctrl_regfile.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-ctrl/rtl/hwpe_ctrl_regfile_latch.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-ctrl/rtl/hwpe_ctrl_slave.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-ctrl/rtl/hwpe_ctrl_seq_mult.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-ctrl/rtl/hwpe_ctrl_ucode.sv
-incdir /volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_package.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_interfaces.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_addressgen.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_fifo_earlystall_sidech.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_fifo_earlystall.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_fifo_scm.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_fifo_sidech.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_fifo.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_buffer.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_merge.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_fence.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_assign.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_split.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_sink.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_source.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_sink_realign.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_source_realign.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_mux_static.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_demux_static.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_tcdm_fifo_load.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_tcdm_fifo_load_sidech.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_tcdm_fifo_store.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_tcdm_mux.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_tcdm_mux_static.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_tcdm_reorder.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-stream/rtl/hwpe_stream_tcdm_reorder_static.sv
-incdir /volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/mac_package.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/parameters.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/32bTO64b.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/mac_ctrl.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/mac_streamer.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/mac_engine.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/mac_top.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/wrap/mac_top_wrap.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/panda_fsm.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/activation_memory.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/adder.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/adder_tree.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/array_pes.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/sparsity_memory.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/output_allignment_padding.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/instruction_memory.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/inner_wrapper_SRAM_act_mem.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/inner_wrapper_SRAM_w_mem.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/outter_wrapper_SRAM_w_mem.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/encoder_FIFO.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/configuration_registers.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/control_unit.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/cpu.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/cpu_wrapper.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/input_buffer.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/multiplier.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/mult_top.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/nonlinear_block.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/pe.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/pooling.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/sig_tanh.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/SRAM_parametrizable_equivalent.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/SRAM_parametrizable_w_equivalent.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/SRAM_parametrizable_s_equivalent.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/SRAM_2048x64_equivalent.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/SRAM_2048x32_equivalent.sv
/volume1/users/vjain/pulpissimo/ips/hwpe-mac-engine/rtl/weight_memory.sv
/volume1/users/vjain/pulpissimo/ips/riscv-dbg/src/dm_pkg.sv
/volume1/users/vjain/pulpissimo/ips/riscv-dbg/debug_rom/debug_rom.sv
/volume1/users/vjain/pulpissimo/ips/riscv-dbg/src/dm_csrs.sv
/volume1/users/vjain/pulpissimo/ips/riscv-dbg/src/dm_mem.sv
/volume1/users/vjain/pulpissimo/ips/riscv-dbg/src/dm_top.sv
/volume1/users/vjain/pulpissimo/ips/riscv-dbg/src/dmi_cdc.sv
/volume1/users/vjain/pulpissimo/ips/riscv-dbg/src/dmi_jtag.sv
/volume1/users/vjain/pulpissimo/ips/riscv-dbg/src/dmi_jtag_tap.sv
/volume1/users/vjain/pulpissimo/ips/riscv-dbg/src/dm_sba.sv
-incdir /volume1/users/vjain/pulpissimo/ips/pulp_soc/../../rtl/includes
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/soc_interconnect.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/boot_rom.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/l2_ram_multi_bank.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/lint_jtag_wrap.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/periph_bus_wrap.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/soc_clk_rst_gen.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/soc_event_arbiter.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/soc_event_generator.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/soc_event_queue.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/soc_interconnect_wrap.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/soc_peripherals.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/pulp_soc/pulp_soc.sv
-incdir /volume1/users/vjain/pulpissimo/ips/pulp_soc/../../rtl/includes
-incdir /volume1/users/vjain/pulpissimo/ips/pulp_soc/.
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/udma_subsystem/udma_subsystem.sv
-incdir /volume1/users/vjain/pulpissimo/ips/pulp_soc/../../rtl/includes
-incdir /volume1/users/vjain/pulpissimo/ips/pulp_soc/.
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/fc/fc_demux.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/fc/fc_subsystem.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/fc/fc_hwpe.sv
-incdir /volume1/users/vjain/pulpissimo/ips/pulp_soc/../../rtl/includes
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/apb_clkdiv.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/apb_timer_unit.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/apb_soc_ctrl.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/memory_models.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/pulp_interfaces.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/axi_slice_dc_master_wrap.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/axi_slice_dc_slave_wrap.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/glitch_free_clk_mux.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/scm_2048x32.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/scm_512x32.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/tcdm_arbiter_2x1.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/apb_wakeup.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/apb_wakeup_counter.sv
-incdir /volume1/users/vjain/pulpissimo/ips/pulp_soc/../../rtl/includes
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/glitch_free_clk_mux.sv
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/apb_dummy.sv
-incdir /volume1/users/vjain/pulpissimo/ips/pulp_soc/../../rtl/includes
/volume1/users/vjain/pulpissimo/ips/pulp_soc/rtl/components/freq_meter.sv
/volume1/users/vjain/pulpissimo/ips/tbtools/dpi_models/dpi_models.sv
/volume1/users/vjain/pulpissimo/ips/tbtools/tb_driver/tb_driver.sv
